---
apiVersion: v1
kind: Service
metadata:
  namespace: moni
  name: prometheus-cadvisor
  labels:
    app: prometheus
    component: cadvisor-core
spec:
  clusterIP: None
  ports:
  - name: scrape
    port: 8080
    protocol: TCP
  selector:
    app: prometheus
    component: cadvisor-core
    type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: prometheus-cadvisor
  namespace: moni
spec:
  template:
    metadata:
      annotations:
         prometheus.io/scrape: 'true'
      labels:
         app: prometheus
         component: cadvisor-core
    spec:
      tolerations:
      - operator: "Exists"
      hostNetwork: true
      containers:
      - name: cadvisor
        image: registry.ekos.local/ekos/cadvisor:v0.24.0
        args: [ "-port=1086", "-profiling=true"]
        resources:
          requests:
            cpu: 200m
            memory: 200M
          limits:
            cpu: 800m
            memory: 800M
        volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: var-run
          mountPath: /var/run
          readOnly: false
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
        ports:
        - name: scrape
          containerPort: 1086
          hostPort: 1086
          protocol: TCP
        securityContext:
          privileged: true
      hostPID: true
      volumes:
        - name: cgroup
          hostPath:
           path: /sys/fs/cgroup
        - name: rootfs
          hostPath:
           path: /
        - name: var-run
          hostPath:
           path: /var/run
        - name: sys
          hostPath:
           path: /sys
        - name: docker
          hostPath:
           path: /var/lib/docker
